spring:
  datasource:
    url: jdbc:sqlite:database.db
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        show_sql: false
        format_sql: true
  data:
    jpa:
      repositories:
        enabled: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    url: jdbc:sqlite:database.db
    driverClassName: org.sqlite.JDBC